In [1]:
import sys, os # sys 시스템 변수 경로를 불러올때 사용
sys.path.append("C:\\Users\\Administrator\\jupyter\\deep-learning-from-scratch-master")
import numpy as np
from dataset.mnist import load_mnist
from PIL import Image #이미지 처리를 도와주는 라이브러리이다.



In [2]:
os.getcwd()

'C:\\Users\\Administrator\\jupyter'

In [3]:
sys.path

['C:\\Users\\Administrator\\jupyter',
 'C:\\ProgramData\\Anaconda3\\python39.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 '',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Administrator\\.ipython',
 'C:\\Users\\Administrator\\jupyter\\deep-learning-from-scratch-master']

In [4]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img)) # np.uint8 은 0~ 256까지의 값을 넘어서지 않게 도와줌
    pil_img.show()

In [5]:
np.uint8(256)

0

In [6]:
np.uint8(257) #언싸인드

1

In [7]:
np.int8(128) #싸인드

-128

In [8]:
np.int8(129) #싸인드

-127

In [9]:
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)
# 60000 x 1 (채널) x28 x 28 (해상도)
img = x_train[0]
label = t_train[0]
print(label)  # 5

#flatten 을 안하면 3차원 텐서상태고 행렬이 아니라서 이미지가 안된다. 
#flatten을 안하고 실행하려면 []을 하나 날려줘야한다.img = x_train[0][0]
print(img.shape)  # (784,) flatten을해서 784 차원 벡터가 된다.28x28  60000 x 784 행렬이 된다.
img = img.reshape(28, 28)  # 형상을 원래 이미지의 크기로 변형
print(img.shape)  # (28, 28)

img_show(img)
#img_show(255-img) 브로드 캐스트 흑백이 반전된다. 

5
(784,)
(28, 28)


In [10]:
import sys
import os
import pickle
import numpy as np
sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
from dataset.mnist import load_mnist
from common.functions import sigmoid, softmax


# 3.6.1 MNIST 데이터셋
'''
0~9 숫자 이미지로 구성.
훈련 이미지 60000장, 시험 이미지 10000장
28*28 크기의 회색조 이미지이며 각 픽셀은 0~255의 값을 가짐
레이블은 정답에 해당하는 숫자
'''
# 처음 한 번은 몇 분 정도 걸림
# 이미지를 numpy 배열로 저장
# flatten : 입력 이미지를 평탄화(1차원 배열로)
# normalize : 입력 이미지를 정규화(0.0~1.0 사이의 값으로)
# one_hot_label : 레이블을 원-핫 인코딩 형태로 저장


(x_train, t_train), (x_test, t_test) = load_mnist(flatten=False,
                                                  normalize=False) #t는 라벨이다.

# 각 데이터의 형상 출력
print(x_train.shape)  # (60000, 784)
print(t_train.shape)  # (60000,)
print(x_test.shape)  # (10000, 784)
print(t_test.shape)  # (10000,)

(60000, 1, 28, 28)
(60000,)
(10000, 1, 28, 28)
(10000,)


In [10]:
np.set_printoptions(linewidth=115,threshold =1000) # linewidth 줄넘김 threshold 1000개까진 표시해주세요
print(x_train[0]) # 이 모양을 Image Matrix라고 한다. flatten을 하면 벡터로된다. 3,3 은 9차원 벡터가 되고 2,2 는 4차원 벡터가 된다.
print(t_train[0])

[[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0
     0]
  [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0
     0]
  [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0
     0]
  [  0   0   0   0   0   0   0  18 219 253 253 2

In [11]:
print(x_train[1])
print(t_train[1])

[[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  51 159 253 159  50   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0   0  48 238 252 252 252 237   0   0   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0   0   0  54 227 253 252 239 233 252  57   6   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0  10  60 224 252 253 252 202  84 252 253 122   0   0   0   0   0
     0]
  [  0   0   0   0   0   0   0   0   0   0   0 1

In [12]:
t_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [13]:
x_train.ndim # mnist를 불러올때 flatten을 해주면 2차원 배열로 나온다. 

4

### 이미지와 텐서

mnist 흑백 이미지 : 행렬 흑, 백  28 x 28  
흑백 이미지의 데이터 : 3차원 텐서 (60000장 x 28 x 28)  

컬러이미지 :  3차원 텐서 앵무새 사진은 빨 초 파  3개를 합쳐놓은것이다. 1920 x1080  
컬러이미지의 데이터 : (4차원 텐서 1920 x1080 x3(3색) x 60000장)

In [14]:
x=np.arange(12)

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x.reshape(1,2,6)

###  matplotlib 활용

In [ ]:
import matplotlib.pyplot as plt
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=False, normalize=False)

plt.figure(figsize=(4,4)) #새로운 figure를 생성해준다. 크기도 바꿀수 있다.
plt.imshow(x_train[0][0]) #위에서 말한 flatten을 false로 실행
plt.colorbar() #256 사이의 값
plt.show()

In [ ]:
#여러개 한번에 표시하기 
plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(x_train[i][0],cmap = plt.cm.binary)
    plt.xlabel(t_train[i])
plt.show()